apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: dev-nginx
data:
  nginx.conf: |
    events { }
    http {
      server {
        listen 8081;
        location / {
          proxy_pass http://server-service.dev-server.svc.cluster.local:8080;
          sub_filter_types *;
          sub_filter "Kubernetes" "Kubernetes & Nginx";
        }
      }
    }
