apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: dev-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: http-echo
  template:
    metadata:
      labels:
        service: http-echo
    spec:
      containers:
      - image: ealen/echo-server
        name: server
        args:
        - --port=8080
        ports:
        - containerPort: 8080
